### ISSUE TITLE
Prepare symposium

### ISSUE THREAD

**Issue by aaronyaosmith** [AguaClara/aide_code#2]
Write and prepare for our symposium on Monday 3/18! Our goal is that other people understand whatever we've been doing for the past semester. We're presenting for 12 minutes: 7:57-8:09 PM.

Deadline: Monday 3/18

#### Links to materials:
[Presentation](https://docs.google.com/presentation/d/18Ioj1Ouxqf0wEGJbXomCN8p8UVov4qU1K9eAbf0kzt8/edit#slide=id.g346a079b2f_0_0)
[Outline for presentation](https://docs.google.com/document/d/1mSIuM2UDALfJv98U4hOPdHY9qMiCKlUsf1JMCPeVzkU/edit)
[Schedule](https://docs.google.com/spreadsheets/d/1kuL0i7Ye9k-4rWXTC8B34sDGDsZs87uMRHfot4amgXw/edit#gid=0)
[Symposium template](https://docs.google.com/presentation/d/1yFygWVcYyZTZ58N2hPtFArOA9gfbs9OwQbCggvnjZS0/edit)
[Grading rubric](https://docs.google.com/document/d/1d-6zhJ2KiKBsWwjjD-v9bqpJcBLIHDJGJmqxxjTJHOU/edit)

**Comment by SinhaVinita** [comment]
Prepared my part and worked on the slides. Done.

**Comment by zhenxiao3** [comment]
Created my slides and notes

**Comment by ericxhm** [comment]
Worked on my part of the presentation.

**Comment by aaronyaosmith** [comment]
Finished preparing the presentation.
