### ISSUE TITLE
Fix LFOM

### ISSUE THREAD

**Issue by aaronyaosmith** [AguaClara/aide_code#4]
Currently the LFOM feature generation script is broken. Let's figure out what's wrong with it and fix it such that it outputs the correct LFOM given its input parameters.

Deadline: 5/10

**Comment by eak24** [comment]
Note that an earlier version is working: https://cad.onshape.com/documents/e1798ab5f546e1414e86992d/v/de28d69f3970b67344d403c4/e/890edb42c7884277d8d8711d hope that helps!

**Comment by aaronyaosmith** [comment]
What I've been doing this week: organized what exactly AIDE Code's plans will be for the rest of the semester. We haven't explicitly laid things out between the planning meeting on 3/28 and now. The plan is for Eric to work on extending the pipe feature as much as possible based on AIDE Template's needs, while the rest of us will work on figuring out what exactly this LFOM needs to be, and making it into a working feature.

**Comment by SinhaVinita** [comment]
Have looked at the code given to us by Design and the working one. Hope to implement a few changes.

**Comment by zhenxiao3** [comment]
I have looked over the old and new LFOM code briefly. Will make changes soon.

**Comment by aaronyaosmith** [comment]
I fixed some issues with configuration variable name changes in the new LFOM model which were causing some cryptic errors, but there still seems to be an issue with the generation of individual holes which I can't find the cause of.

**Comment by zhenxiao3** [comment]
I've also been looking at the LFOM code for issues to find why the holes arent generating.

**Comment by SinhaVinita** [comment]
The holes aren't generating and I'm looking into sample code from Onshape library and forum to figure it out. Will make more progress this week.

**Comment by zhenxiao3** [comment]
We located the differences between the old and new code and saw that the calculation for the orifice angle was different. After changing it, the LFOM function seems to work again.

**Comment by aaronyaosmith** [comment]
Like Zhen said, we've managed to fix the LFOM by changing the orifice angle calculation from using the row spacing value (which was incorrect) to using the input orifice distance. We're speculating that the issue came from holes wrapping around the LFOM: the row spacing value is much larger than the orifice distance, which would cause wrapping even at small row lengths.

**Comment by SinhaVinita** [comment]
The LFOM code is working now. The necessary changes were made after contrasting the old and the current versions of the LFOM code. The issue is closed.

**Comment by SinhaVinita** [comment]
The LFOM code is working now. The necessary changes were made after contrasting the old and the current versions of the LFOM code. The issue is closed.
