### ISSUE TITLE
Prepare and film final presentation

### ISSUE THREAD

**Issue by aaronyaosmith** [AguaClara/aide_code#5]
We're filming our final presentation 2:00pm, Saturday May 4! Let's determine who's saying what and prepare for filming. The presentation is available for editing [here](https://docs.google.com/presentation/d/1_ls3Ms2Rst1Rpk0gp8LCo4C6eCvKO2BkAUOMofBuLts/edit#slide=id.g496275e098_0_0). See the AIDE Code repo for previous presentations.

Our presentation will be 12 minutes long.

Deadline: 5/4

**Comment by ericxhm** [comment]
Finished the presentation slides and the filming of the presentation

**Comment by SinhaVinita** [comment]
Finished preparing and presentation of slides on LFOM part of the presentation.

**Comment by zhenxiao3** [comment]
finished preparing slides and recording the presentation

**Comment by aaronyaosmith** [comment]
Prepared slides and recorded the presentation! Videos will be available once AguaClara leadership edits them.
